// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import util from 'node:util';

import Fuse from 'fuse.js';
import ts from 'typescript';

import { WorkerInput, WorkerSuccess, WorkerError } from './code-tool-types';
import { Telnyx } from 'telnyx';

function getRunFunctionNode(
  code: string,
): ts.FunctionDeclaration | ts.FunctionExpression | ts.ArrowFunction | null {
  const sourceFile = ts.createSourceFile('code.ts', code, ts.ScriptTarget.Latest, true);

  for (const statement of sourceFile.statements) {
    // Check for top-level function declarations
    if (ts.isFunctionDeclaration(statement)) {
      if (statement.name?.text === 'run') {
        return statement;
      }
    }

    // Check for variable declarations: const run = () => {} or const run = function() {}
    if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        if (ts.isIdentifier(declaration.name) && declaration.name.text === 'run') {
          // Check if it's initialized with a function
          if (
            declaration.initializer &&
            (ts.isFunctionExpression(declaration.initializer) || ts.isArrowFunction(declaration.initializer))
          ) {
            return declaration.initializer;
          }
        }
      }
    }
  }

  return null;
}

const fuse = new Fuse(
  [
    'client.legacy.reporting.batchDetailRecords.messaging.create',
    'client.legacy.reporting.batchDetailRecords.messaging.delete',
    'client.legacy.reporting.batchDetailRecords.messaging.list',
    'client.legacy.reporting.batchDetailRecords.messaging.retrieve',
    'client.legacy.reporting.batchDetailRecords.speechToText.create',
    'client.legacy.reporting.batchDetailRecords.speechToText.delete',
    'client.legacy.reporting.batchDetailRecords.speechToText.list',
    'client.legacy.reporting.batchDetailRecords.speechToText.retrieve',
    'client.legacy.reporting.batchDetailRecords.voice.create',
    'client.legacy.reporting.batchDetailRecords.voice.delete',
    'client.legacy.reporting.batchDetailRecords.voice.list',
    'client.legacy.reporting.batchDetailRecords.voice.retrieve',
    'client.legacy.reporting.batchDetailRecords.voice.retrieveFields',
    'client.legacy.reporting.usageReports.retrieveSpeechToText',
    'client.legacy.reporting.usageReports.messaging.create',
    'client.legacy.reporting.usageReports.messaging.delete',
    'client.legacy.reporting.usageReports.messaging.list',
    'client.legacy.reporting.usageReports.messaging.retrieve',
    'client.legacy.reporting.usageReports.numberLookup.create',
    'client.legacy.reporting.usageReports.numberLookup.delete',
    'client.legacy.reporting.usageReports.numberLookup.list',
    'client.legacy.reporting.usageReports.numberLookup.retrieve',
    'client.legacy.reporting.usageReports.voice.create',
    'client.legacy.reporting.usageReports.voice.delete',
    'client.legacy.reporting.usageReports.voice.list',
    'client.legacy.reporting.usageReports.voice.retrieve',
    'client.oauth.grants',
    'client.oauth.introspect',
    'client.oauth.register',
    'client.oauth.retrieve',
    'client.oauth.retrieveAuthorize',
    'client.oauth.retrieveJwks',
    'client.oauth.token',
    'client.oauthClients.create',
    'client.oauthClients.delete',
    'client.oauthClients.list',
    'client.oauthClients.retrieve',
    'client.oauthClients.update',
    'client.oauthGrants.delete',
    'client.oauthGrants.list',
    'client.oauthGrants.retrieve',
    'client.webhooks.unsafeUnwrap',
    'client.webhooks.unwrap',
    'client.accessIPAddress.create',
    'client.accessIPAddress.delete',
    'client.accessIPAddress.list',
    'client.accessIPAddress.retrieve',
    'client.accessIPRanges.create',
    'client.accessIPRanges.delete',
    'client.accessIPRanges.list',
    'client.actions.purchase.create',
    'client.actions.register.create',
    'client.addresses.create',
    'client.addresses.delete',
    'client.addresses.list',
    'client.addresses.retrieve',
    'client.addresses.actions.acceptSuggestions',
    'client.addresses.actions.validate',
    'client.advancedOrders.create',
    'client.advancedOrders.list',
    'client.advancedOrders.retrieve',
    'client.advancedOrders.updateRequirementGroup',
    'client.ai.retrieveModels',
    'client.ai.summarize',
    'client.ai.assistants.chat',
    'client.ai.assistants.clone',
    'client.ai.assistants.create',
    'client.ai.assistants.delete',
    'client.ai.assistants.getTexml',
    'client.ai.assistants.import',
    'client.ai.assistants.list',
    'client.ai.assistants.retrieve',
    'client.ai.assistants.sendSMS',
    'client.ai.assistants.update',
    'client.ai.assistants.tests.create',
    'client.ai.assistants.tests.delete',
    'client.ai.assistants.tests.list',
    'client.ai.assistants.tests.retrieve',
    'client.ai.assistants.tests.update',
    'client.ai.assistants.tests.testSuites.list',
    'client.ai.assistants.tests.testSuites.runs.list',
    'client.ai.assistants.tests.testSuites.runs.trigger',
    'client.ai.assistants.tests.runs.list',
    'client.ai.assistants.tests.runs.retrieve',
    'client.ai.assistants.tests.runs.trigger',
    'client.ai.assistants.canaryDeploys.create',
    'client.ai.assistants.canaryDeploys.delete',
    'client.ai.assistants.canaryDeploys.retrieve',
    'client.ai.assistants.canaryDeploys.update',
    'client.ai.assistants.scheduledEvents.create',
    'client.ai.assistants.scheduledEvents.delete',
    'client.ai.assistants.scheduledEvents.list',
    'client.ai.assistants.scheduledEvents.retrieve',
    'client.ai.assistants.tools.test',
    'client.ai.assistants.versions.delete',
    'client.ai.assistants.versions.list',
    'client.ai.assistants.versions.promote',
    'client.ai.assistants.versions.retrieve',
    'client.ai.assistants.versions.update',
    'client.ai.audio.transcribe',
    'client.ai.chat.createCompletion',
    'client.ai.clusters.compute',
    'client.ai.clusters.delete',
    'client.ai.clusters.fetchGraph',
    'client.ai.clusters.list',
    'client.ai.clusters.retrieve',
    'client.ai.conversations.addMessage',
    'client.ai.conversations.create',
    'client.ai.conversations.delete',
    'client.ai.conversations.list',
    'client.ai.conversations.retrieve',
    'client.ai.conversations.retrieveConversationsInsights',
    'client.ai.conversations.update',
    'client.ai.conversations.insightGroups.delete',
    'client.ai.conversations.insightGroups.insightGroups',
    'client.ai.conversations.insightGroups.retrieve',
    'client.ai.conversations.insightGroups.retrieveInsightGroups',
    'client.ai.conversations.insightGroups.update',
    'client.ai.conversations.insightGroups.insights.assign',
    'client.ai.conversations.insightGroups.insights.deleteUnassign',
    'client.ai.conversations.insights.create',
    'client.ai.conversations.insights.delete',
    'client.ai.conversations.insights.list',
    'client.ai.conversations.insights.retrieve',
    'client.ai.conversations.insights.update',
    'client.ai.conversations.messages.list',
    'client.ai.embeddings.create',
    'client.ai.embeddings.list',
    'client.ai.embeddings.retrieve',
    'client.ai.embeddings.similaritySearch',
    'client.ai.embeddings.url',
    'client.ai.embeddings.buckets.delete',
    'client.ai.embeddings.buckets.list',
    'client.ai.embeddings.buckets.retrieve',
    'client.ai.fineTuning.jobs.cancel',
    'client.ai.fineTuning.jobs.create',
    'client.ai.fineTuning.jobs.list',
    'client.ai.fineTuning.jobs.retrieve',
    'client.ai.integrations.list',
    'client.ai.integrations.retrieve',
    'client.ai.integrations.connections.delete',
    'client.ai.integrations.connections.list',
    'client.ai.integrations.connections.retrieve',
    'client.ai.mcpServers.create',
    'client.ai.mcpServers.delete',
    'client.ai.mcpServers.list',
    'client.ai.mcpServers.retrieve',
    'client.ai.mcpServers.update',
    'client.auditEvents.list',
    'client.authenticationProviders.create',
    'client.authenticationProviders.delete',
    'client.authenticationProviders.list',
    'client.authenticationProviders.retrieve',
    'client.authenticationProviders.update',
    'client.availablePhoneNumberBlocks.list',
    'client.availablePhoneNumbers.list',
    'client.balance.retrieve',
    'client.billingGroups.create',
    'client.billingGroups.delete',
    'client.billingGroups.list',
    'client.billingGroups.retrieve',
    'client.billingGroups.update',
    'client.brand.create',
    'client.brand.delete',
    'client.brand.getFeedback',
    'client.brand.list',
    'client.brand.resend2faEmail',
    'client.brand.retrieve',
    'client.brand.revet',
    'client.brand.update',
    'client.brand.externalVetting.import',
    'client.brand.externalVetting.list',
    'client.brand.externalVetting.order',
    'client.bulkSimCardActions.list',
    'client.bulkSimCardActions.retrieve',
    'client.bundlePricing.billingBundles.list',
    'client.bundlePricing.billingBundles.retrieve',
    'client.bundlePricing.userBundles.create',
    'client.bundlePricing.userBundles.deactivate',
    'client.bundlePricing.userBundles.list',
    'client.bundlePricing.userBundles.listResources',
    'client.bundlePricing.userBundles.listUnused',
    'client.bundlePricing.userBundles.retrieve',
    'client.callControlApplications.create',
    'client.callControlApplications.delete',
    'client.callControlApplications.list',
    'client.callControlApplications.retrieve',
    'client.callControlApplications.update',
    'client.callEvents.list',
    'client.calls.dial',
    'client.calls.retrieveStatus',
    'client.calls.actions.answer',
    'client.calls.actions.bridge',
    'client.calls.actions.enqueue',
    'client.calls.actions.gather',
    'client.calls.actions.gatherUsingAI',
    'client.calls.actions.gatherUsingAudio',
    'client.calls.actions.gatherUsingSpeak',
    'client.calls.actions.hangup',
    'client.calls.actions.leaveQueue',
    'client.calls.actions.pauseRecording',
    'client.calls.actions.refer',
    'client.calls.actions.reject',
    'client.calls.actions.resumeRecording',
    'client.calls.actions.sendDtmf',
    'client.calls.actions.sendSipInfo',
    'client.calls.actions.speak',
    'client.calls.actions.startAIAssistant',
    'client.calls.actions.startForking',
    'client.calls.actions.startNoiseSuppression',
    'client.calls.actions.startPlayback',
    'client.calls.actions.startRecording',
    'client.calls.actions.startSiprec',
    'client.calls.actions.startStreaming',
    'client.calls.actions.startTranscription',
    'client.calls.actions.stopAIAssistant',
    'client.calls.actions.stopForking',
    'client.calls.actions.stopGather',
    'client.calls.actions.stopNoiseSuppression',
    'client.calls.actions.stopPlayback',
    'client.calls.actions.stopRecording',
    'client.calls.actions.stopSiprec',
    'client.calls.actions.stopStreaming',
    'client.calls.actions.stopTranscription',
    'client.calls.actions.switchSupervisorRole',
    'client.calls.actions.transfer',
    'client.calls.actions.updateClientState',
    'client.campaign.acceptSharing',
    'client.campaign.deactivate',
    'client.campaign.getMnoMetadata',
    'client.campaign.getOperationStatus',
    'client.campaign.getSharingStatus',
    'client.campaign.list',
    'client.campaign.retrieve',
    'client.campaign.submitAppeal',
    'client.campaign.update',
    'client.campaign.usecase.getCost',
    'client.campaign.osr.getAttributes',
    'client.campaignBuilder.create',
    'client.campaignBuilder.brand.qualifyByUsecase',
    'client.channelZones.list',
    'client.channelZones.update',
    'client.chargesBreakdown.retrieve',
    'client.chargesSummary.retrieve',
    'client.comments.create',
    'client.comments.list',
    'client.comments.markAsRead',
    'client.comments.retrieve',
    'client.conferences.create',
    'client.conferences.list',
    'client.conferences.listParticipants',
    'client.conferences.retrieve',
    'client.conferences.actions.hold',
    'client.conferences.actions.join',
    'client.conferences.actions.leave',
    'client.conferences.actions.mute',
    'client.conferences.actions.play',
    'client.conferences.actions.recordPause',
    'client.conferences.actions.recordResume',
    'client.conferences.actions.recordStart',
    'client.conferences.actions.recordStop',
    'client.conferences.actions.speak',
    'client.conferences.actions.stop',
    'client.conferences.actions.unhold',
    'client.conferences.actions.unmute',
    'client.conferences.actions.update',
    'client.connections.list',
    'client.connections.listActiveCalls',
    'client.connections.retrieve',
    'client.countryCoverage.retrieve',
    'client.countryCoverage.retrieveCountry',
    'client.credentialConnections.create',
    'client.credentialConnections.delete',
    'client.credentialConnections.list',
    'client.credentialConnections.retrieve',
    'client.credentialConnections.update',
    'client.credentialConnections.actions.checkRegistrationStatus',
    'client.customStorageCredentials.create',
    'client.customStorageCredentials.delete',
    'client.customStorageCredentials.retrieve',
    'client.customStorageCredentials.update',
    'client.customerServiceRecords.create',
    'client.customerServiceRecords.list',
    'client.customerServiceRecords.retrieve',
    'client.customerServiceRecords.verifyPhoneNumberCoverage',
    'client.detailRecords.list',
    'client.dialogflowConnections.create',
    'client.dialogflowConnections.delete',
    'client.dialogflowConnections.retrieve',
    'client.dialogflowConnections.update',
    'client.documentLinks.list',
    'client.documents.delete',
    'client.documents.download',
    'client.documents.generateDownloadLink',
    'client.documents.list',
    'client.documents.retrieve',
    'client.documents.update',
    'client.documents.upload',
    'client.documents.uploadJson',
    'client.dynamicEmergencyAddresses.create',
    'client.dynamicEmergencyAddresses.delete',
    'client.dynamicEmergencyAddresses.list',
    'client.dynamicEmergencyAddresses.retrieve',
    'client.dynamicEmergencyEndpoints.create',
    'client.dynamicEmergencyEndpoints.delete',
    'client.dynamicEmergencyEndpoints.list',
    'client.dynamicEmergencyEndpoints.retrieve',
    'client.enum.retrieve',
    'client.externalConnections.create',
    'client.externalConnections.delete',
    'client.externalConnections.list',
    'client.externalConnections.retrieve',
    'client.externalConnections.update',
    'client.externalConnections.updateLocation',
    'client.externalConnections.logMessages.dismiss',
    'client.externalConnections.logMessages.list',
    'client.externalConnections.logMessages.retrieve',
    'client.externalConnections.civicAddresses.list',
    'client.externalConnections.civicAddresses.retrieve',
    'client.externalConnections.phoneNumbers.list',
    'client.externalConnections.phoneNumbers.retrieve',
    'client.externalConnections.phoneNumbers.update',
    'client.externalConnections.releases.list',
    'client.externalConnections.releases.retrieve',
    'client.externalConnections.uploads.create',
    'client.externalConnections.uploads.list',
    'client.externalConnections.uploads.pendingCount',
    'client.externalConnections.uploads.refreshStatus',
    'client.externalConnections.uploads.retrieve',
    'client.externalConnections.uploads.retry',
    'client.faxApplications.create',
    'client.faxApplications.delete',
    'client.faxApplications.list',
    'client.faxApplications.retrieve',
    'client.faxApplications.update',
    'client.faxes.create',
    'client.faxes.delete',
    'client.faxes.list',
    'client.faxes.retrieve',
    'client.faxes.actions.cancel',
    'client.faxes.actions.refresh',
    'client.fqdnConnections.create',
    'client.fqdnConnections.delete',
    'client.fqdnConnections.list',
    'client.fqdnConnections.retrieve',
    'client.fqdnConnections.update',
    'client.fqdns.create',
    'client.fqdns.delete',
    'client.fqdns.list',
    'client.fqdns.retrieve',
    'client.fqdns.update',
    'client.globalIPAllowedPorts.list',
    'client.globalIPAssignmentHealth.retrieve',
    'client.globalIPAssignments.create',
    'client.globalIPAssignments.delete',
    'client.globalIPAssignments.list',
    'client.globalIPAssignments.retrieve',
    'client.globalIPAssignments.update',
    'client.globalIPAssignmentsUsage.retrieve',
    'client.globalIPHealthCheckTypes.list',
    'client.globalIPHealthChecks.create',
    'client.globalIPHealthChecks.delete',
    'client.globalIPHealthChecks.list',
    'client.globalIPHealthChecks.retrieve',
    'client.globalIPLatency.retrieve',
    'client.globalIPProtocols.list',
    'client.globalIPUsage.retrieve',
    'client.globalIPs.create',
    'client.globalIPs.delete',
    'client.globalIPs.list',
    'client.globalIPs.retrieve',
    'client.inboundChannels.list',
    'client.inboundChannels.update',
    'client.integrationSecrets.create',
    'client.integrationSecrets.delete',
    'client.integrationSecrets.list',
    'client.inventoryCoverage.list',
    'client.invoices.list',
    'client.invoices.retrieve',
    'client.ipConnections.create',
    'client.ipConnections.delete',
    'client.ipConnections.list',
    'client.ipConnections.retrieve',
    'client.ipConnections.update',
    'client.ips.create',
    'client.ips.delete',
    'client.ips.list',
    'client.ips.retrieve',
    'client.ips.update',
    'client.ledgerBillingGroupReports.create',
    'client.ledgerBillingGroupReports.retrieve',
    'client.list.retrieveAll',
    'client.list.retrieveByZone',
    'client.managedAccounts.create',
    'client.managedAccounts.getAllocatableGlobalOutboundChannels',
    'client.managedAccounts.list',
    'client.managedAccounts.retrieve',
    'client.managedAccounts.update',
    'client.managedAccounts.updateGlobalChannelLimit',
    'client.managedAccounts.actions.disable',
    'client.managedAccounts.actions.enable',
    'client.media.delete',
    'client.media.download',
    'client.media.list',
    'client.media.retrieve',
    'client.media.update',
    'client.media.upload',
    'client.messages.cancelScheduled',
    'client.messages.retrieve',
    'client.messages.schedule',
    'client.messages.send',
    'client.messages.sendGroupMms',
    'client.messages.sendLongCode',
    'client.messages.sendNumberPool',
    'client.messages.sendShortCode',
    'client.messages.rcs.generateDeeplink',
    'client.messaging.rcs.inviteTestNumber',
    'client.messaging.rcs.listBulkCapabilities',
    'client.messaging.rcs.retrieveCapabilities',
    'client.messaging.rcs.agents.list',
    'client.messaging.rcs.agents.retrieve',
    'client.messaging.rcs.agents.update',
    'client.messagingHostedNumberOrders.checkEligibility',
    'client.messagingHostedNumberOrders.create',
    'client.messagingHostedNumberOrders.createVerificationCodes',
    'client.messagingHostedNumberOrders.delete',
    'client.messagingHostedNumberOrders.list',
    'client.messagingHostedNumberOrders.retrieve',
    'client.messagingHostedNumberOrders.validateCodes',
    'client.messagingHostedNumberOrders.actions.uploadFile',
    'client.messagingHostedNumbers.delete',
    'client.messagingNumbersBulkUpdates.create',
    'client.messagingNumbersBulkUpdates.retrieve',
    'client.messagingOptouts.list',
    'client.messagingProfiles.create',
    'client.messagingProfiles.delete',
    'client.messagingProfiles.list',
    'client.messagingProfiles.listPhoneNumbers',
    'client.messagingProfiles.listShortCodes',
    'client.messagingProfiles.retrieve',
    'client.messagingProfiles.update',
    'client.messagingProfiles.autorespConfigs.create',
    'client.messagingProfiles.autorespConfigs.delete',
    'client.messagingProfiles.autorespConfigs.list',
    'client.messagingProfiles.autorespConfigs.retrieve',
    'client.messagingProfiles.autorespConfigs.update',
    'client.messagingTollfree.verification.requests.create',
    'client.messagingTollfree.verification.requests.delete',
    'client.messagingTollfree.verification.requests.list',
    'client.messagingTollfree.verification.requests.retrieve',
    'client.messagingTollfree.verification.requests.update',
    'client.messagingURLDomains.list',
    'client.messsages.rcs',
    'client.mobileNetworkOperators.list',
    'client.mobilePushCredentials.create',
    'client.mobilePushCredentials.delete',
    'client.mobilePushCredentials.list',
    'client.mobilePushCredentials.retrieve',
    'client.networkCoverage.list',
    'client.networks.create',
    'client.networks.delete',
    'client.networks.list',
    'client.networks.listInterfaces',
    'client.networks.retrieve',
    'client.networks.update',
    'client.networks.defaultGateway.create',
    'client.networks.defaultGateway.delete',
    'client.networks.defaultGateway.retrieve',
    'client.notificationChannels.create',
    'client.notificationChannels.delete',
    'client.notificationChannels.list',
    'client.notificationChannels.retrieve',
    'client.notificationChannels.update',
    'client.notificationEventConditions.list',
    'client.notificationEvents.list',
    'client.notificationProfiles.create',
    'client.notificationProfiles.delete',
    'client.notificationProfiles.list',
    'client.notificationProfiles.retrieve',
    'client.notificationProfiles.update',
    'client.notificationSettings.create',
    'client.notificationSettings.delete',
    'client.notificationSettings.list',
    'client.notificationSettings.retrieve',
    'client.numberBlockOrders.create',
    'client.numberBlockOrders.list',
    'client.numberBlockOrders.retrieve',
    'client.numberLookup.retrieve',
    'client.numberOrderPhoneNumbers.list',
    'client.numberOrderPhoneNumbers.retrieve',
    'client.numberOrderPhoneNumbers.updateRequirementGroup',
    'client.numberOrderPhoneNumbers.updateRequirements',
    'client.numberOrders.create',
    'client.numberOrders.list',
    'client.numberOrders.retrieve',
    'client.numberOrders.update',
    'client.numberReservations.create',
    'client.numberReservations.list',
    'client.numberReservations.retrieve',
    'client.numberReservations.actions.extend',
    'client.numbersFeatures.create',
    'client.operatorConnect.actions.refresh',
    'client.otaUpdates.list',
    'client.otaUpdates.retrieve',
    'client.outboundVoiceProfiles.create',
    'client.outboundVoiceProfiles.delete',
    'client.outboundVoiceProfiles.list',
    'client.outboundVoiceProfiles.retrieve',
    'client.outboundVoiceProfiles.update',
    'client.payment.autoRechargePrefs.list',
    'client.payment.autoRechargePrefs.update',
    'client.phoneNumberAssignmentByProfile.assign',
    'client.phoneNumberAssignmentByProfile.retrievePhoneNumberStatus',
    'client.phoneNumberAssignmentByProfile.retrieveStatus',
    'client.phoneNumberBlocks.jobs.deletePhoneNumberBlock',
    'client.phoneNumberBlocks.jobs.list',
    'client.phoneNumberBlocks.jobs.retrieve',
    'client.phoneNumberCampaigns.create',
    'client.phoneNumberCampaigns.delete',
    'client.phoneNumberCampaigns.list',
    'client.phoneNumberCampaigns.retrieve',
    'client.phoneNumberCampaigns.update',
    'client.phoneNumbers.delete',
    'client.phoneNumbers.list',
    'client.phoneNumbers.retrieve',
    'client.phoneNumbers.slimList',
    'client.phoneNumbers.update',
    'client.phoneNumbers.actions.changeBundleStatus',
    'client.phoneNumbers.actions.enableEmergency',
    'client.phoneNumbers.actions.verifyOwnership',
    'client.phoneNumbers.csvDownloads.create',
    'client.phoneNumbers.csvDownloads.list',
    'client.phoneNumbers.csvDownloads.retrieve',
    'client.phoneNumbers.jobs.deleteBatch',
    'client.phoneNumbers.jobs.list',
    'client.phoneNumbers.jobs.retrieve',
    'client.phoneNumbers.jobs.updateBatch',
    'client.phoneNumbers.jobs.updateEmergencySettingsBatch',
    'client.phoneNumbers.messaging.list',
    'client.phoneNumbers.messaging.retrieve',
    'client.phoneNumbers.messaging.update',
    'client.phoneNumbers.voice.list',
    'client.phoneNumbers.voice.retrieve',
    'client.phoneNumbers.voice.update',
    'client.phoneNumbers.voicemail.create',
    'client.phoneNumbers.voicemail.retrieve',
    'client.phoneNumbers.voicemail.update',
    'client.phoneNumbersRegulatoryRequirements.retrieve',
    'client.portabilityChecks.run',
    'client.porting.listUkCarriers',
    'client.porting.events.list',
    'client.porting.events.republish',
    'client.porting.events.retrieve',
    'client.porting.reports.create',
    'client.porting.reports.list',
    'client.porting.reports.retrieve',
    'client.porting.loaConfigurations.create',
    'client.porting.loaConfigurations.delete',
    'client.porting.loaConfigurations.list',
    'client.porting.loaConfigurations.preview0',
    'client.porting.loaConfigurations.preview1',
    'client.porting.loaConfigurations.retrieve',
    'client.porting.loaConfigurations.update',
    'client.portingOrders.create',
    'client.portingOrders.delete',
    'client.portingOrders.list',
    'client.portingOrders.retrieve',
    'client.portingOrders.retrieveAllowedFocWindows',
    'client.portingOrders.retrieveExceptionTypes',
    'client.portingOrders.retrieveLoaTemplate',
    'client.portingOrders.retrieveRequirements',
    'client.portingOrders.retrieveSubRequest',
    'client.portingOrders.update',
    'client.portingOrders.phoneNumberConfigurations.create',
    'client.portingOrders.phoneNumberConfigurations.list',
    'client.portingOrders.actions.activate',
    'client.portingOrders.actions.cancel',
    'client.portingOrders.actions.confirm',
    'client.portingOrders.actions.share',
    'client.portingOrders.activationJobs.list',
    'client.portingOrders.activationJobs.retrieve',
    'client.portingOrders.activationJobs.update',
    'client.portingOrders.additionalDocuments.create',
    'client.portingOrders.additionalDocuments.delete',
    'client.portingOrders.additionalDocuments.list',
    'client.portingOrders.comments.create',
    'client.portingOrders.comments.list',
    'client.portingOrders.verificationCodes.list',
    'client.portingOrders.verificationCodes.send',
    'client.portingOrders.verificationCodes.verify',
    'client.portingOrders.actionRequirements.initiate',
    'client.portingOrders.actionRequirements.list',
    'client.portingOrders.associatedPhoneNumbers.create',
    'client.portingOrders.associatedPhoneNumbers.delete',
    'client.portingOrders.associatedPhoneNumbers.list',
    'client.portingOrders.phoneNumberBlocks.create',
    'client.portingOrders.phoneNumberBlocks.delete',
    'client.portingOrders.phoneNumberBlocks.list',
    'client.portingOrders.phoneNumberExtensions.create',
    'client.portingOrders.phoneNumberExtensions.delete',
    'client.portingOrders.phoneNumberExtensions.list',
    'client.portingPhoneNumbers.list',
    'client.portouts.list',
    'client.portouts.listRejectionCodes',
    'client.portouts.retrieve',
    'client.portouts.updateStatus',
    'client.portouts.events.list',
    'client.portouts.events.republish',
    'client.portouts.events.retrieve',
    'client.portouts.reports.create',
    'client.portouts.reports.list',
    'client.portouts.reports.retrieve',
    'client.portouts.comments.create',
    'client.portouts.comments.list',
    'client.portouts.supportingDocuments.create',
    'client.portouts.supportingDocuments.list',
    'client.privateWirelessGateways.create',
    'client.privateWirelessGateways.delete',
    'client.privateWirelessGateways.list',
    'client.privateWirelessGateways.retrieve',
    'client.publicInternetGateways.create',
    'client.publicInternetGateways.delete',
    'client.publicInternetGateways.list',
    'client.publicInternetGateways.retrieve',
    'client.queues.retrieve',
    'client.queues.calls.list',
    'client.queues.calls.remove',
    'client.queues.calls.retrieve',
    'client.queues.calls.update',
    'client.recordingTranscriptions.delete',
    'client.recordingTranscriptions.list',
    'client.recordingTranscriptions.retrieve',
    'client.recordings.delete',
    'client.recordings.list',
    'client.recordings.retrieve',
    'client.recordings.actions.delete',
    'client.regions.list',
    'client.regulatoryRequirements.retrieve',
    'client.reports.listMdrs',
    'client.reports.listWdrs',
    'client.reports.cdrUsageReports.fetchSync',
    'client.reports.mdrUsageReports.create',
    'client.reports.mdrUsageReports.delete',
    'client.reports.mdrUsageReports.fetchSync',
    'client.reports.mdrUsageReports.list',
    'client.reports.mdrUsageReports.retrieve',
    'client.requirementGroups.create',
    'client.requirementGroups.delete',
    'client.requirementGroups.list',
    'client.requirementGroups.retrieve',
    'client.requirementGroups.submitForApproval',
    'client.requirementGroups.update',
    'client.requirementTypes.list',
    'client.requirementTypes.retrieve',
    'client.requirements.list',
    'client.requirements.retrieve',
    'client.roomCompositions.create',
    'client.roomCompositions.delete',
    'client.roomCompositions.list',
    'client.roomCompositions.retrieve',
    'client.roomParticipants.list',
    'client.roomParticipants.retrieve',
    'client.roomRecordings.delete',
    'client.roomRecordings.deleteBulk',
    'client.roomRecordings.list',
    'client.roomRecordings.retrieve',
    'client.rooms.create',
    'client.rooms.delete',
    'client.rooms.list',
    'client.rooms.retrieve',
    'client.rooms.update',
    'client.rooms.actions.generateJoinClientToken',
    'client.rooms.actions.refreshClientToken',
    'client.rooms.sessions.list0',
    'client.rooms.sessions.list1',
    'client.rooms.sessions.retrieve',
    'client.rooms.sessions.retrieveParticipants',
    'client.rooms.sessions.actions.end',
    'client.rooms.sessions.actions.kick',
    'client.rooms.sessions.actions.mute',
    'client.rooms.sessions.actions.unmute',
    'client.seti.retrieveBlackBoxTestResults',
    'client.shortCodes.list',
    'client.shortCodes.retrieve',
    'client.shortCodes.update',
    'client.simCardDataUsageNotifications.create',
    'client.simCardDataUsageNotifications.delete',
    'client.simCardDataUsageNotifications.list',
    'client.simCardDataUsageNotifications.retrieve',
    'client.simCardDataUsageNotifications.update',
    'client.simCardGroups.create',
    'client.simCardGroups.delete',
    'client.simCardGroups.list',
    'client.simCardGroups.retrieve',
    'client.simCardGroups.update',
    'client.simCardGroups.actions.list',
    'client.simCardGroups.actions.removePrivateWirelessGateway',
    'client.simCardGroups.actions.removeWirelessBlocklist',
    'client.simCardGroups.actions.retrieve',
    'client.simCardGroups.actions.setPrivateWirelessGateway',
    'client.simCardGroups.actions.setWirelessBlocklist',
    'client.simCardOrderPreview.preview',
    'client.simCardOrders.create',
    'client.simCardOrders.list',
    'client.simCardOrders.retrieve',
    'client.simCards.delete',
    'client.simCards.getActivationCode',
    'client.simCards.getDeviceDetails',
    'client.simCards.getPublicIP',
    'client.simCards.list',
    'client.simCards.listWirelessConnectivityLogs',
    'client.simCards.retrieve',
    'client.simCards.update',
    'client.simCards.actions.bulkSetPublicIPs',
    'client.simCards.actions.disable',
    'client.simCards.actions.enable',
    'client.simCards.actions.list',
    'client.simCards.actions.removePublicIP',
    'client.simCards.actions.retrieve',
    'client.simCards.actions.setPublicIP',
    'client.simCards.actions.setStandby',
    'client.simCards.actions.validateRegistrationCodes',
    'client.siprecConnectors.create',
    'client.siprecConnectors.delete',
    'client.siprecConnectors.retrieve',
    'client.siprecConnectors.update',
    'client.storage.listMigrationSourceCoverage',
    'client.storage.buckets.createPresignedURL',
    'client.storage.buckets.sslCertificate.create',
    'client.storage.buckets.sslCertificate.delete',
    'client.storage.buckets.sslCertificate.retrieve',
    'client.storage.buckets.usage.getAPIUsage',
    'client.storage.buckets.usage.getBucketUsage',
    'client.storage.migrationSources.create',
    'client.storage.migrationSources.delete',
    'client.storage.migrationSources.list',
    'client.storage.migrationSources.retrieve',
    'client.storage.migrations.create',
    'client.storage.migrations.list',
    'client.storage.migrations.retrieve',
    'client.storage.migrations.actions.stop',
    'client.subNumberOrders.cancel',
    'client.subNumberOrders.list',
    'client.subNumberOrders.retrieve',
    'client.subNumberOrders.update',
    'client.subNumberOrders.updateRequirementGroup',
    'client.subNumberOrdersReport.create',
    'client.subNumberOrdersReport.download',
    'client.subNumberOrdersReport.retrieve',
    'client.telephonyCredentials.create',
    'client.telephonyCredentials.createToken',
    'client.telephonyCredentials.delete',
    'client.telephonyCredentials.list',
    'client.telephonyCredentials.retrieve',
    'client.telephonyCredentials.update',
    'client.texml.secrets',
    'client.texml.accounts.retrieveRecordingsJson',
    'client.texml.accounts.retrieveTranscriptionsJson',
    'client.texml.accounts.calls.calls',
    'client.texml.accounts.calls.retrieve',
    'client.texml.accounts.calls.retrieveCalls',
    'client.texml.accounts.calls.siprecJson',
    'client.texml.accounts.calls.streamsJson',
    'client.texml.accounts.calls.update',
    'client.texml.accounts.calls.recordingsJson.recordingsJson',
    'client.texml.accounts.calls.recordingsJson.retrieveRecordingsJson',
    'client.texml.accounts.calls.recordings.recordingSidJson',
    'client.texml.accounts.calls.siprec.siprecSidJson',
    'client.texml.accounts.calls.streams.streamingSidJson',
    'client.texml.accounts.conferences.retrieve',
    'client.texml.accounts.conferences.retrieveConferences',
    'client.texml.accounts.conferences.retrieveRecordings',
    'client.texml.accounts.conferences.retrieveRecordingsJson',
    'client.texml.accounts.conferences.update',
    'client.texml.accounts.conferences.participants.delete',
    'client.texml.accounts.conferences.participants.participants',
    'client.texml.accounts.conferences.participants.retrieve',
    'client.texml.accounts.conferences.participants.retrieveParticipants',
    'client.texml.accounts.conferences.participants.update',
    'client.texml.accounts.recordings.json.deleteRecordingSidJson',
    'client.texml.accounts.recordings.json.retrieveRecordingSidJson',
    'client.texml.accounts.transcriptions.json.deleteRecordingTranscriptionSidJson',
    'client.texml.accounts.transcriptions.json.retrieveRecordingTranscriptionSidJson',
    'client.texml.calls.initiate',
    'client.texml.calls.update',
    'client.texmlApplications.create',
    'client.texmlApplications.delete',
    'client.texmlApplications.list',
    'client.texmlApplications.retrieve',
    'client.texmlApplications.update',
    'client.textToSpeech.generateSpeech',
    'client.textToSpeech.listVoices',
    'client.usageReports.getOptions',
    'client.usageReports.list',
    'client.userAddresses.create',
    'client.userAddresses.list',
    'client.userAddresses.retrieve',
    'client.userTags.list',
    'client.verifications.retrieve',
    'client.verifications.triggerCall',
    'client.verifications.triggerFlashcall',
    'client.verifications.triggerSMS',
    'client.verifications.byPhoneNumber.list',
    'client.verifications.byPhoneNumber.actions.verify',
    'client.verifications.actions.verify',
    'client.verifiedNumbers.create',
    'client.verifiedNumbers.delete',
    'client.verifiedNumbers.list',
    'client.verifiedNumbers.retrieve',
    'client.verifiedNumbers.actions.submitVerificationCode',
    'client.verifyProfiles.create',
    'client.verifyProfiles.createTemplate',
    'client.verifyProfiles.delete',
    'client.verifyProfiles.list',
    'client.verifyProfiles.retrieve',
    'client.verifyProfiles.retrieveTemplates',
    'client.verifyProfiles.update',
    'client.verifyProfiles.updateTemplate',
    'client.virtualCrossConnects.create',
    'client.virtualCrossConnects.delete',
    'client.virtualCrossConnects.list',
    'client.virtualCrossConnects.retrieve',
    'client.virtualCrossConnects.update',
    'client.virtualCrossConnectsCoverage.list',
    'client.webhookDeliveries.list',
    'client.webhookDeliveries.retrieve',
    'client.wireguardInterfaces.create',
    'client.wireguardInterfaces.delete',
    'client.wireguardInterfaces.list',
    'client.wireguardInterfaces.retrieve',
    'client.wireguardPeers.create',
    'client.wireguardPeers.delete',
    'client.wireguardPeers.list',
    'client.wireguardPeers.retrieve',
    'client.wireguardPeers.retrieveConfig',
    'client.wireguardPeers.update',
    'client.wireless.retrieveRegions',
    'client.wireless.detailRecordsReports.create',
    'client.wireless.detailRecordsReports.delete',
    'client.wireless.detailRecordsReports.list',
    'client.wireless.detailRecordsReports.retrieve',
    'client.wirelessBlocklistValues.list',
    'client.wirelessBlocklists.create',
    'client.wirelessBlocklists.delete',
    'client.wirelessBlocklists.list',
    'client.wirelessBlocklists.retrieve',
    'client.wirelessBlocklists.update',
    'client.partnerCampaigns.list',
    'client.partnerCampaigns.listSharedByMe',
    'client.partnerCampaigns.retrieve',
    'client.partnerCampaigns.retrieveSharingStatus',
    'client.partnerCampaigns.update',
    'client.wellKnown.retrieveAuthorizationServerMetadata',
    'client.wellKnown.retrieveProtectedResourceMetadata',
    'client.inexplicitNumberOrders.create',
    'client.inexplicitNumberOrders.list',
    'client.inexplicitNumberOrders.retrieve',
  ],
  { threshold: 1, shouldSort: true },
);

function getMethodSuggestions(fullyQualifiedMethodName: string): string[] {
  return fuse
    .search(fullyQualifiedMethodName)
    .map(({ item }) => item)
    .slice(0, 5);
}

const proxyToObj = new WeakMap<any, any>();
const objToProxy = new WeakMap<any, any>();

type ClientProxyConfig = {
  path: string[];
  isBelievedBad?: boolean;
};

function makeSdkProxy<T extends object>(obj: T, { path, isBelievedBad = false }: ClientProxyConfig): T {
  let proxy: T = objToProxy.get(obj);

  if (!proxy) {
    proxy = new Proxy(obj, {
      get(target, prop, receiver) {
        const propPath = [...path, String(prop)];
        const value = Reflect.get(target, prop, receiver);

        if (isBelievedBad || (!(prop in target) && value === undefined)) {
          // If we're accessing a path that doesn't exist, it will probably eventually error.
          // Let's proxy it and mark it bad so that we can control the error message.
          // We proxy an empty class so that an invocation or construction attempt is possible.
          return makeSdkProxy(class {}, { path: propPath, isBelievedBad: true });
        }

        if (value !== null && (typeof value === 'object' || typeof value === 'function')) {
          return makeSdkProxy(value, { path: propPath, isBelievedBad });
        }

        return value;
      },

      apply(target, thisArg, args) {
        if (isBelievedBad || typeof target !== 'function') {
          const fullyQualifiedMethodName = path.join('.');
          const suggestions = getMethodSuggestions(fullyQualifiedMethodName);
          throw new Error(
            `${fullyQualifiedMethodName} is not a function. Did you mean: ${suggestions.join(', ')}`,
          );
        }

        return Reflect.apply(target, proxyToObj.get(thisArg) ?? thisArg, args);
      },

      construct(target, args, newTarget) {
        if (isBelievedBad || typeof target !== 'function') {
          const fullyQualifiedMethodName = path.join('.');
          const suggestions = getMethodSuggestions(fullyQualifiedMethodName);
          throw new Error(
            `${fullyQualifiedMethodName} is not a constructor. Did you mean: ${suggestions.join(', ')}`,
          );
        }

        return Reflect.construct(target, args, newTarget);
      },
    });

    objToProxy.set(obj, proxy);
    proxyToObj.set(proxy, obj);
  }

  return proxy;
}

function parseError(code: string, error: unknown): string | undefined {
  if (!(error instanceof Error)) return;
  const message = error.name ? `${error.name}: ${error.message}` : error.message;
  try {
    // Deno uses V8; the first "<anonymous>:LINE:COLUMN" is the top of stack.
    const lineNumber = error.stack?.match(/<anonymous>:([0-9]+):[0-9]+/)?.[1];
    // -1 for the zero-based indexing
    const line =
      lineNumber &&
      code
        .split('\n')
        .at(parseInt(lineNumber, 10) - 1)
        ?.trim();
    return line ? `${message}\n  at line ${lineNumber}\n    ${line}` : message;
  } catch {
    return message;
  }
}

const fetch = async (req: Request): Promise<Response> => {
  const { opts, code } = (await req.json()) as WorkerInput;
  if (code == null) {
    return Response.json(
      {
        message:
          'The code param is missing. Provide one containing a top-level `run` function. Write code within this template:\n\n```\nasync function run(client) {\n  // Fill this out\n}\n```',
      } satisfies WorkerError,
      { status: 400, statusText: 'Code execution error' },
    );
  }

  const runFunctionNode = getRunFunctionNode(code);
  if (!runFunctionNode) {
    return Response.json(
      {
        message:
          'The code is missing a top-level `run` function. Write code within this template:\n\n```\nasync function run(client) {\n  // Fill this out\n}\n```',
      } satisfies WorkerError,
      { status: 400, statusText: 'Code execution error' },
    );
  }

  const client = new Telnyx({
    ...opts,
  });

  const logLines: string[] = [];
  const errLines: string[] = [];
  const console = {
    log: (...args: unknown[]) => {
      logLines.push(util.format(...args));
    },
    error: (...args: unknown[]) => {
      errLines.push(util.format(...args));
    },
  };
  try {
    let run_ = async (client: any) => {};
    eval(`${code}\nrun_ = run;`);
    const result = await run_(makeSdkProxy(client, { path: ['client'] }));
    return Response.json({
      result,
      logLines,
      errLines,
    } satisfies WorkerSuccess);
  } catch (e) {
    return Response.json(
      {
        message: parseError(code, e),
      } satisfies WorkerError,
      { status: 400, statusText: 'Code execution error' },
    );
  }
};

export default { fetch };
