configured_endpoints: 865
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/telnyx%2Ftelnyx-08edfbd77dee1d6dbe8a0d660e3ba19653a71a0270f4bdfecfabf1508db658ee.yml
openapi_spec_hash: 2c8f26d09aa0b88dec6fc6d9fbc6fbf8
config_hash: 39f40ef7ed65fa1cf1db9eadf9a0b5e7
