configured_endpoints: 799
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/telnyx%2Ftelnyx-fa9c1416f0ff7bcefaef8d3edc10cb8b427904b2eb3985abfe7ca84cdc9f557a.yml
openapi_spec_hash: 2db979a8acd6212fc12b7ef408cfdbe0
config_hash: 6ec507ea09296a834701d38daa151b4f
