configured_endpoints: 922
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/telnyx%2Ftelnyx-a6affef3fce65caf688297e6adb9898a6ac1c0e3edfc77f8ad3668d2c863e75f.yml
openapi_spec_hash: 322c77ccca34be35be168bfac5c91627
config_hash: 96f32c4a46b0defbee33c185f119eee0
