on:
  release:
    types: [released]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: >
            We have a new ${{github.event.release.tag_name}} release of our
            ${{ fromJson('{
              "team-telnyx/telnyx-python": "Python",
              "team-telnyx/telnyx-ruby": "Ruby",
              "team-telnyx/telnyx-node": "Node",
              "team-telnyx/telnyx-java": "Java",
              "team-telnyx/telnyx-dotnet": "Dotnet",
              "team-telnyx/telnyx-php": "PHP"
            }')[github.event.repository.full_name] }} SDK!
            Check out the details here: ${{ github.event.release.html_url }}
          consumer-key: ${{ secrets.TWITTER_HANDLE_TELNYX_DEV_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_HANDLE_TELNYX_DEV_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_HANDLE_TELNYX_DEV_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_HANDLE_TELNYX_DEV_ACCESS_TOKEN_SECRET }}
